<?php

namespace MainBundle\Repository;

/**
 * BadCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadCommentsRepository extends \Doctrine\ORM\EntityRepository
{
}
